zone       = "ru-central1-b"
cloud_id   = "b1gu9piqq14p2h00buhe"
folder_id  = "b1gjolnnoe2770jcqeg5"
yc_mysql_db = "netology_db"
yc_mysql_user = "netology_user"
yc_mysql_pass = "netology_pass"
yc_kube_ver = "1.21"